config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/chat", to: "home#chat"
  get "/new", to: "home#new"
  get "/info", to: "home#info"
  get "/calendar", to: "home#calendar"
  get "/form", to: "home#form"
  get "/alert", to: "home#alert"
  # Defines the root path route ("/")
  # root "articles#index"
  get "/profile", to: "profile#index"
  get "/profile/edit", to: "profile#edit"

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.all
  end 
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
    def index
        
    end

    def edit
        
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/home/alert.html.erb
<h1> Send an Alert</h1>

<%= form_with model: @user do |form| %>
    <div>
        <%= form.label :"Board Member's Name" %><br>
        <%= form.text_field :name %>
    </div>

    <div>
        <%= form.label :"Board Member's Email"%> <br>
        <%= form.text_field :email %>
    </div>

    <div>
        <%= form.label :"Community Name"%> <br>
        <%= form.text_field :community %>
    </div>

    <div>
        <%= form.label :alert%> <br>
        <%= form.text_field :alert %>
    </div>

    <div> 
        <%= form.submit('Submit') %>
    </div>
    <button> Complain Instead </button>
<% end %>

app/views/home/calendar.html.erb
<h1> Calendar </h1>

app/views/home/chat.html.erb
<h1> Chat Page </h1>
<h3> Talk to other users </h3>

<button> Create Chat </button>
<h4> Welcome, John Smith</h4>

app/views/home/form.html.erb
<h1> Complaint Form</h1>
<h2> We are here to help! </h2>
<%= form_with model: @user do |form| %>
    <div>
        <%= form.label :"Complainant's Name" %><br>
        <%= form.text_field :name %>
    </div>

    <div>
        <%= form.label :"Complainant's Email"%> <br>
        <%= form.text_field :email %>
    </div>

    <div>
        <%= form.label :"Community Name"%> <br>
        <%= form.text_field :community %>
    </div>

    <div>
        <%= form.label :'This complaint is regarding: '%> <br>
        <%= form.text_field :complaint %>
    </div>

    <div> 
        <%= form.submit('Submit') %>        
    </div>

    <button> Alert Instead </button>
<% end %>

app/views/home/index.html.erb
<h1 class="text-primary text-center"><del>HoaFinder.com</del></h1>
<h1 class="text-primary text-center">HoaHub.com Landing Page</h1>
<p class="text-secondary text-center text-danger">yay look bootstrap :D</p>
<p class="text-secondary text-center text-danger">Retrieve from DB Example: <%= @user.last.username %></p>

<ul>
<li><%= link_to "Chat", chat_path %></li>
<li><%= link_to "Info", info_path %></li>
<li><%= link_to "Calendar", calendar_path %></li>
<li><%= link_to "Edit Profile", profile_edit_path %></li>
</ul>

app/views/home/info.html.erb
<h1> Community Info </h1>

app/views/home/new.html.erb
<h1> New Resident Registration</h1>